#!/bin/sh
# This do script can be directly invoked, for bootstrapping with
# $  sh @all.do
# $  redo @all

set -e

sh $(dirname $0)/build

# create docs 
xargs -L1 -i bin/redux redo doc/{}.1 doc/{}.html < LINKS
