.TH redo-ifcreate 1 "February 02, 2014" "Redux User Manual"
.SH NAME
.PP
ifcreate - Creates dependency on non-existence of targets.
.SH SYNOPSIS
.PP
redux ifcreate [TARGET...]
.SH OPTIONS
.PP
-?=false: Show help
.PP
-h=false: Show help
.PP
-help=false: Show help
.SH NOTES
.PP
The ifcreate command creates a dependency on the non-existence of the
target files.
The current file will be invalidated if the target comes into existence.
If the target exists, the command returns an error.
.SH DESCRIPTION
.PP
This command can be invoked as \f[C]redux\ ifcreate\f[] or, through a
symlink, as \f[C]redo-ifcreate\f[].
.PP
The \f[C]ifcreate\f[] command marks the current target as out of date
when a non-existent prerequisite file comes into existence or is
deleted.
.PP
This command should be placed in a do file and not run directly.
.SH AUTHORS
Gyepi Sam.
